import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3d9f59cf-cf57-4d60-8873-51889795f70e/AIR+MONARCH+IV.png",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    comments: [
      { name: "John Smith", comment: "Great shoes, very comfortable!" },
      { name: "Emma Wilson", comment: "Perfect fit and excellent quality." },
      { name: "Michael Brown", comment: "Stylish design, would recommend!" },
    ],
    views: 89,
    sold: 45,
  },
  {
    id: 2,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/sntgaggdpbvuopmeg9az/AIR+VAPORMAX+PLUS.png",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    comments: [
      { name: "Sarah Jones", comment: "Love the color and design!" },
      { name: "David Miller", comment: "Best running shoes I've ever owned." },
      { name: "Jennifer Lee", comment: "Very durable and comfortable." },
    ],
    views: 75,
    sold: 62,
  },

  {
    id: 3,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/749fe60b-503d-48ea-afbd-a22411cf905e/NIKE+WAFFLE+NAV.png",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    comments: [
      { name: "Robert Taylor", comment: "These sneakers are awesome for daily use!" },
      { name: "Lisa Anderson", comment: "Great grip and support for my feet." },
      { name: "James Wilson", comment: "The green color is even better in person." },
    ],
    views: 63,
    sold: 47,
  },
  {
    id: 4,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d1745604-ef91-449a-955f-fbde43daf49e/NIKE+FREE+RN+5.0+NEXT+NATURE.png",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
    comments: [
      { name: "Thomas Garcia", comment: "Perfect for long distance running!" },
      { name: "Sophia Martinez", comment: "Great cushioning and support." },
      { name: "William Johnson", comment: "Very lightweight and comfortable." },
    ],
    views: 92,
    sold: 78,
  },
  {
    id: 5,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a4fc576e-1f35-4ae0-b598-b308cd7795e2/W+NIKE+DUNK+LOW+NEXT+NATURE.png",
    title: "Nike Dunk Low Next Nature",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "brown",
    category: "sneakers",
    comments: [
      { name: "Olivia White", comment: "So comfortable for everyday wear!" },
      { name: "Daniel Thompson", comment: "Great quality for the price." },
      { name: "Emily Clark", comment: "Perfect fit and very stylish." },
    ],
    views: 57,
    sold: 42,
  },
  {
    id: 6,
    img: "https://assets.adidas.com/images/w_1880,f_auto,q_auto/237264d18bb14f108f80e83ba4644ffb_9366/IF7086_01_standard.jpg",
    title: "Handball Spezial",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "Grey",
    category: "Sneakrs",
    comments: [
      { name: "Jessica Adams", comment: "So elegant and comfortable!" },
      { name: "Andrew Wilson", comment: "My wife loves these flats." },
      { name: "Natalie Moore", comment: "Perfect for work and casual wear." },
    ],
    views: 49,
    sold: 61,
  },

  {
    id: 7,
    img: "https://assets.adidas.com/images/w_1880,f_auto,q_auto/4d5d7b1ca06a44bab576af15010496b0_9366/GX2272_01_standard.jpg",
    title: "Rivalry Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Addidas",
    color: "white",
    category: "sneakrs",
    views: 38,
    sold: 29,
  },

  {
    id: 8,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2b889abe-49b5-4a0b-bb76-82acf92616fd/W+NIKE+ZOOM+VOMERO+5.png",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    views: 76,
    sold: 52,
  },

  {
    id: 9,
    img: "https://www.prada.com/content/dam/pradabkg_products/1/1X9/1X962N/P39F0009/1X962N_P39_F0009_F_035_SLR.jpg/_jcr_content/renditions/cq5dam.web.hebebed.2000.2000.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1300,00",
    newPrice: "1200",
    company: "Prada",
    color: "black",
    category: "sandals",
    views: 82,
    sold: 67,
  },

  {
    id: 10,
    img: "https://www.bally.com/media-images/s/files/1/0651/9206/7329/files/BALLY_WP550X_VT727_U901_01.jpg?v=1718339424",
    title: "Ballyrina Mary-Jane Pump In Black Leather",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Bally",
    color: "Black",
    category: "heels",
    views: 64,
    sold: 37,
  },
  {
    id: 11,
    img: "https://www.bally.com/media-images/s/files/1/0651/9206/7329/files/BALLY_WP3001_VT821_U101_01.jpg?v=1733553867",
    title: "Ballyrina Pump in White Leather",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "heels",
    views: 71,
    sold: 43,
  },
  {
    id: 12,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6f8b91aa-c3af-4116-978a-c0a37e65789e/W+NIKE+ZOOM+VOMERO+5.png",
    title: "Nike Zoom Vomero 5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "blue",
    category: "sneakers",
    views: 59,
    sold: 31,
  },
  {
    id: 13,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a46fd8b7-d6fd-44d1-be30-fd3f7c8ebdae/COURT+BOROUGH+MID+2+%28PSV%29.png",
    title: "Nike Court Borough Mid 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "white",
    category: "sneakers",
    views: 47,
    sold: 25,
  },
  {
    id: 14,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/931fbbf0-a384-40a2-99a2-c74841551a5d/AIR+FORCE+1+%2707+LV8.png",
    title: "Nike Air Force 1 '07 LV8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "Purple",
    category: "sneakers",
    views: 53,
    sold: 39,
  },

  {
    id: 15,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ef837cb6-3d1a-4d09-b23c-dc7c41d2c9e2/AIR+FORCE+1+%2707+LV8.png",
    title: "Nike Air Force 1 '07 LV8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Nike",
    color: "black",
    category: "sneakers",
    views: 68,
    sold: 42,
  },
  {
    id: 16,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9c61c6e-31b5-4112-a161-7966c1eb4c4d/AIR+FORCE+1+LV8+3+%28GS%29.png",
    title: "Nike Air Force 1 LV8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Nike",
    color: "red",
    category: "sneakers",
    views: 51,
    sold: 27,
  },
  {
    id: 17,
    img: "https://assets.vans.eu/images/t_Thumbnail/VN000CQA2BO-HERO/premium-authentic-44-schuhe.png",
    title: "Vans authentique",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats",
    views: 44,
    sold: 33,
  },
  {
    id: 18,
    img: "https://assets.vans.eu/images/t_Thumbnail/VN000CR5OVM-HERO/chaussures-old-skool.png",
    title: "Vans old skool",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats",
    views: 58,
    sold: 36,
  },
  {
    id: 19,
    img: "https://assets.vans.eu/images/t_img/c_fill,g_center,f_auto,h_815,w_652,e_unsharp_mask:100/dpr_2.0/v1730392725/VN000D3HY28-HERO/Old-Skool-Shoes.png",
    title: "Vans old skool",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "flats",
    views: 72,
    sold: 48,
  },

  {
    id: 22,
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f12b8cd3-de52-4971-8ec9-caec4175b21d/NIKE+COURT+LEGACY+%28PSV%29.png",
    title: "Nike court Legacy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
    views: 83,
    sold: 62,
  },
  
];

export default data;